name: Test, Build, and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to build and release (e.g., 1.0.0.0)'
        required: false
  push:
    branches:
      - master
    paths:
      - 'mirror/**'
      - 'src/**'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write # Needed to create releases
  pages: write    # Needed to deploy to GitHub Pages
  id-token: write # Needed for authentication for GitHub Pages deployment

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.VERSION }}
    steps:
      - name: Set Version
        id: versioning
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            VERSION_MAJOR=1
            VERSION_MINOR=0

            current_seconds=$(date -u +%s)
            start_seconds=$(date -u -d "2025-11-09" +%s)
            VERSION_BUILD=$(( (current_seconds - start_seconds) / 86400 ))

            seconds_today=$(( current_seconds % 86400 ))
            VERSION_REVISION=$(( seconds_today / 2 ))

            VERSION="$VERSION_MAJOR.$VERSION_MINOR.$VERSION_BUILD.$VERSION_REVISION"
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          fi
          echo "Generated version: $VERSION"

  test:
    name: Run All Tests
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          lfs: true
      - name: Run tests
        run: make docker-test

  build:
    name: Build Binaries
    needs: [prepare, test]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: windows-zip
            os: windows-latest
          - target: linux-zip
            os: ubuntu-latest
          - target: linux-appimage
            os: ubuntu-latest
          - target: linux-deb
            os: ubuntu-latest
          - target: linux-rpm
            os: ubuntu-latest
          - target: linux-flatpak
            os: ubuntu-latest
          - target: browser
            os: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          lfs: true
      - name: Install Make on Windows (using winget)
        if: runner.os == 'Windows'
        run: choco install make
      - name: Run Build Process
        shell: pwsh
        run: make docker-publish-${{ matrix.target }} VERSION=${{ needs.prepare.outputs.version }}
      - name: Upload Build Artifact
        if: ${{ matrix.target }} != 'browser'
        uses: actions/upload-artifact@v5
        with:
          name: output-${{ matrix.target }}
          path: ./out
      - name: Upload Browser Artifact for GitHub Pages
        if: ${{ matrix.target }} == 'browser'
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./out/wwwroot

  release:
    name: Create GitHub Release
    needs: [prepare, build]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ needs.prepare.outputs.version }}
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          lfs: true
      - name: Download all build artifacts
        uses: actions/download-artifact@v6
        with:
          path: ./artifacts
      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          draft: true
          generate_release_notes: true
          files: |
            ./artifacts/output-windows-zip/*
            ./artifacts/output-linux-zip/*
            ./artifacts/output-linux-appimage/*
            ./artifacts/output-linux-deb/*
            ./artifacts/output-linux-rpm/*
            ./artifacts/output-linux-flatpak/*

  deploy-pages:
    name: Deploy to GitHub Pages
    needs: release
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4