name: Test, Build, and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to build and release (e.g., 1.0.0.0)'
        required: false
  push:
    branches:
      - master
    paths:
      - 'mirror/**'
      - 'src/**'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write # Needed to create releases
  pages: write    # Needed to deploy to GitHub Pages
  id-token: write # Needed for authentication for GitHub Pages deployment

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.VERSION }}
    steps:
      - name: Set Version
        id: versioning
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            VERSION_MAJOR=1
            VERSION_MINOR=0

            current_seconds=$(date -u +%s)
            start_seconds=$(date -u -d "2025-11-09" +%s)
            VERSION_BUILD=$(( (current_seconds - start_seconds) / 86400 ))

            seconds_today=$(( current_seconds % 86400 ))
            VERSION_REVISION=$(( seconds_today / 2 ))

            VERSION="$VERSION_MAJOR.$VERSION_MINOR.$VERSION_BUILD.$VERSION_REVISION"
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          fi
          echo "Generated version: $VERSION"

  test:
    name: Run All Tests
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Checkout LFS (Cached)
        uses: ./.github/actions/cached-lfs-checkout
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Debug LFS files
        run: |
          file src/AvaloniaXKCD.Tests/Verify/Outputs/*.png
          head -n 5 src/AvaloniaXKCD.Tests/Verify/Outputs/*.png
      - name: Prerequisites for tests
        run: make setup-playwright
      - name: Run tests
        run: make test

  build:
    name: Build Binaries
    needs: [prepare, test]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: windows-zip
            os: windows-2022
          - target: linux-zip
            os: ubuntu-latest
          - target: linux-appimage
            os: ubuntu-latest
          - target: linux-deb
            os: ubuntu-latest
          - target: linux-rpm
            os: ubuntu-latest
          - target: linux-flatpak
            os: ubuntu-latest
          - target: browser
            os: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Checkout LFS (Cached)
        uses: ./.github/actions/cached-lfs-checkout
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Run Build Process
        shell: pwsh
        run: make publish-${{ matrix.target }} VERSION=${{ needs.prepare.outputs.version }}
      - name: Upload Build Artifact
        if: ${{ matrix.target != 'browser' }}
        uses: actions/upload-artifact@v5
        with:
          name: output-${{ matrix.target }}
          path: ./out
      - name: Upload Browser Artifact for GitHub Pages
        if: ${{ matrix.target == 'browser' }}
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./out/wwwroot

  release:
    name: Create GitHub Release
    needs: [prepare, build]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ needs.prepare.outputs.version }}
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          lfs: true
      - name: Create or Update Release
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const repoName = "${{ github.repository }}".split('/')[1];
            let existingRelease = undefined;
            try {
              existingRelease = await github.rest.repos.getReleaseByTag({
                owner: "${{ github.repository_owner }}",
                repo: repoName,
                tag: "v${{ needs.prepare.outputs.version }}"
              });
            } catch {}

            let releaseId = undefined;
            let uploadUrl = undefined;

            if (existingRelease?.status === 200) {
              releaseId = existingRelease.data.id;
              uploadUrl = existingRelease.data.upload_url;

              await github.rest.repos.updateRelease({
                owner: "${{ github.repository_owner }}",
                repo: repoName,
                release_id: releaseId,
                body: "**AXKCD - _Release v${{ needs.prepare.outputs.version }}_**<br/>",
                prerelease: true,
                draft: false,
              });

              const existingAssets = await github.rest.repos.listReleaseAssets({
                owner: "${{ github.repository_owner }}",
                repo: repoName,
                release_id: releaseId
              });
              for (const asset of existingAssets.data) {
                await github.rest.repos.deleteReleaseAsset({
                  owner: "${{ github.repository_owner }}",
                  repo: repoName,
                  asset_id: asset.id
                });
              }
            } else {
              const releaseResponse = await github.rest.repos.createRelease({
                  body: "**AXKCD - _Release v${{ needs.prepare.outputs.version }}_**<br/>",
                  name: "v${{ needs.prepare.outputs.version }}",
                  make_latest: "true",
                  owner: "${{ github.repository_owner }}",
                  prerelease: true,
                  draft: false,
                  repo: repoName,
                  target_commitish: "${{ github.sha }}",
                  tag_name: "v${{ needs.prepare.outputs.version }}"
              });
              releaseId = releaseResponse.data.id;
              uploadUrl = releaseResponse.data.upload_url;
            }

            if (releaseId == undefined) throw new Error("ReleaseID is undefined");
            if (uploadUrl == undefined) throw new Error("UploadURL is undefined");

            const allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: '${{ github.run_id }}',
            });

            const artifactsFolder = path.join(process.env.GITHUB_WORKSPACE, 'artifacts');
            if (!fs.existsSync(artifactsFolder)) {
              fs.mkdirSync(artifactsFolder);
            }

            for (let prefix of ["output-"]) {
              const matchingArtifacts = allArtifacts.data.artifacts.filter((artifact) => {
                return artifact.name.startsWith(prefix);
              });
              if (matchingArtifacts.length < 0) continue;

              for (let matchArtifact of matchingArtifacts) {
                const download = await github.rest.actions.downloadArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: matchArtifact.id,
                  archive_format: 'zip',
                });

                const filePath = path.join(artifactsFolder, `${prefix}${{ needs.prepare.outputs.version }}.zip`);
                const fileBuffer = Buffer.from(download.data);
                fs.writeFileSync(filePath, fileBuffer);

                const uploadResponse = await github.rest.repos.uploadReleaseAsset({
                    url: uploadUrl,
                    headers: {
                        "content-length": download.headers['content-length'],
                        "content-type": download.headers['content-type']
                    },
                    data: download.data,
                    name: prefix + "${{ needs.prepare.outputs.version }}.zip",
                    owner: "${{ github.repository_owner }}",
                    release_id: releaseId,
                    repo: repoName
                });
              }
            }

  deploy-pages:
    name: Deploy to GitHub Pages
    needs: release
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4