name: Sync

on:
  workflow_dispatch:
  schedule:
    # Run at 00:00, 06:00, 12:00, and 18:00 UTC on every Monday, Wednesday, and Friday.
    - cron: '0 */6 * * 1,3,5'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: sync-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Sync:
    name: "Sync"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
        with:
          lfs: true
      - name: Sync
        id: sync
        run: make docker-sync
      - name: Commit Changes to Repository
        if: github.ref == 'refs/heads/main' && github.repository == 'dylanlangston/resume'
        id: commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git add .
          git commit -m "Update: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" || echo "No changes to commit"
          git push origin main